packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - sharp

overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  tmp@<=0.2.3: '>=0.2.4'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=5.0.0 <5.4.15: '>=5.4.15'
  vite@>=5.0.0 <5.4.16: '>=5.4.16'
  vite@>=5.0.0 <5.4.17: '>=5.4.17'
  vite@>=5.0.0 <5.4.18: '>=5.4.18'
  vite@>=5.0.0 <=5.4.18: '>=5.4.19'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
